name: app_fichar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase (versiones compatibles entre sí)
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  

  # Utilidades
  table_calendar: ^3.0.9
  intl: ^0.20.2
  file_picker: ^10.2.0
  url_launcher: ^6.1.10
  flutter_email_sender: ^7.0.0
  provider: ^6.1.2
  google_sign_in: ^6.1.4
  path_provider: ^2.0.15
  open_file: ^3.2.1
  timezone: ^0.10.1
  universal_html: ^2.0.8
  shared_preferences: ^2.5.3
  lottie: ^3.3.1
  flutter_launcher_icons: ^0.14.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/images/ic_launcher_round.png"
    web:
      generate: true
      image_path: "assets/images/ic_launcher_round.png"
flutter:
  uses-material-design: true

  assets:
    - assets/lottie/login_animation.json
    - assets/lottie/splash_animation.json
    # Puedes añadir más rutas si lo necesitas, por ejemplo:
    # - assets/images/
    # - assets/animations/