// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByRAs1DLdr6_DBDlm--ajSHR5V2R_dJ38',
    appId: '1:6248056615:web:b75d9cff234edaf2b9cb02',
    messagingSenderId: '6248056615',
    projectId: 'appfichar-118e1',
    authDomain: 'appfichar-118e1.firebaseapp.com',
    storageBucket: 'appfichar-118e1.firebasestorage.app',
    measurementId: 'G-9QX66YTWKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2mvi1Wvm8qhMYtAPYbyENkcRJNYr_Lds',
    appId: '1:6248056615:android:191f0517ca1e55c1b9cb02',
    messagingSenderId: '6248056615',
    projectId: 'appfichar-118e1',
    storageBucket: 'appfichar-118e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo4N87hFqUya3YGYrgPul_5KBztwjtH8M',
    appId: '1:6248056615:ios:30f1c3f8f9babc42b9cb02',
    messagingSenderId: '6248056615',
    projectId: 'appfichar-118e1',
    storageBucket: 'appfichar-118e1.firebasestorage.app',
    iosBundleId: 'com.example.appFichar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo4N87hFqUya3YGYrgPul_5KBztwjtH8M',
    appId: '1:6248056615:ios:30f1c3f8f9babc42b9cb02',
    messagingSenderId: '6248056615',
    projectId: 'appfichar-118e1',
    storageBucket: 'appfichar-118e1.firebasestorage.app',
    iosBundleId: 'com.example.appFichar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByRAs1DLdr6_DBDlm--ajSHR5V2R_dJ38',
    appId: '1:6248056615:web:e90a5a0a41cb0e92b9cb02',
    messagingSenderId: '6248056615',
    projectId: 'appfichar-118e1',
    authDomain: 'appfichar-118e1.firebaseapp.com',
    storageBucket: 'appfichar-118e1.firebasestorage.app',
    measurementId: 'G-S6X9GZT3BG',
  );
}
